# Generated by Django 2.0.13 on 2019-06-17 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='game',
            field=models.CharField(default='Game:', max_length=200),
        ),
    ]
