# Generated by Django 2.0.13 on 2019-06-17 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_gamepublisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='genre',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='game',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='gamepublisher',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
